### ISSUE TITLE
Message constants not working

### ISSUE THREAD

**Issue by pbeeson** [RethinkRobotics-opensource/rosnodejs_examples#5]
ROS Messages with [Constants](https://wiki.ros.org/msg#Constants) do not seem to work in rosnodejs.  The resulting message type when printed using console.log does not constant any message fields that have been assigned value.

**Comment by chris-smith** [comment]
I'll need more information about what you're doing and how you're generating messages (gennodejs, rosnodejs static messages, rosnodejs on the fly).

```
const rosnodejs = require('./rosnodejs');
const action_msgs = rosnodejs.require('actionlib_msgs');
console.log(action_msgs.msg.GoalStatus);
/* Prints
[Function: GoalStatus] {
  Constants: {
    PENDING: 0,
    ACTIVE: 1,
    PREEMPTED: 2,
    SUCCEEDED: 3,
    ABORTED: 4,
    REJECTED: 5,
    PREEMPTING: 6,
    RECALLING: 7,
    RECALLED: 8,
    LOST: 9
  }
}
*/
```

**Comment by pbeeson** [comment]
I see.  I didn't notice that there was a constants field in the message.  Thanks
